### ISSUE TITLE
Problems building the package

### ISSUE THREAD

**Issue by aroslov** [Hacklone/angular2-cool-http#3]
Hi there,

I'm having issues with building the package from sources: npm install Hacklone/angular2-cool-http followed by npm run build gives me 

```
$ npm run build

> angular2-cool-http@1.1.3 build /Users/anton/Downloads/angular2-cool/node_modules/angular2-cool-http
> rm -rf ./dist && tsc --project tsconfig-es5.json && tsc --project tsconfig-es2015.json && cp ./README.md ./dist/README.md && cp ./package.json ./dist/package.json

error TS5014: Failed to parse file 'tsconfig-es5.json/tsconfig.json': Unexpected token u.

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
```

From npm-debug.log:

```
14 verbose stack Error: angular2-cool-http@1.1.3 build: `rm -rf ./dist && tsc --project tsconfig-es5.json && tsc --project tsconfig-es2015.json && cp ./README.md ./dist/README.md && cp ./package.json ./dist/package.json`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid angular2-cool-http@1.1.3
16 verbose cwd /Users/anton/Downloads/angular2-cool/node_modules/angular2-cool-http
17 error Darwin 15.5.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
19 error node v5.4.0
20 error npm  v3.3.12
```

I'm trying to build it like this because installing the package by default from npm repo for whatever reason gives me JS files with ES6 syntax (`let cookieCollection = this.getCookieCollection();`) which breaks in ES5 only browsers (like desktop & mobile Safari).

Any help with this is highly appreciated.

**Comment by Hacklone** [comment]
Hey,

what typescript version is installed on your computer?
The problem is with prsing the tsconfig json:

error TS5014: Failed to parse file 'tsconfig-es5.json/tsconfig.json': Unexpected token u.

Barna

**Comment by Hacklone** [comment]
closing due to inactivity
